name: Beta releases

on:
  push:
    branches: [master, TownOfUs]
  pull_request:
    branches: [master, TownOfUs]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 5.0.100

      - name: Install dependencies
        run: dotnet restore "AUCapture-WPF\AUCapture-WPF.csproj"

      - name: Publish
        run: |
          dotnet publish "AUCapture-WPF\AUCapture-WPF.csproj" -p:PublishProfile=DevProfile

      - name: Relocate
        run: |
          mv AUCapture-WPF\\bin\\Release\\netcoreapp3.1\\publish\\AUCapture-WPF.exe ..\AmongUsCapture-Beta.exe

      - name: Zip
        run: |
          7z a AmongUsCapture-Beta.zip ..\AmongUsCapture-Beta.exe -mx=9
      
      - name: AmongUsCapture-beta
        uses: actions/upload-artifact@v4
        with:
          name: AmongUsCapture-beta
          path: AmongUsCapture-Beta.zip
